package com.litongjava.modules.dev.tools.file.sync.model;

import com.litongjava.modules.dev.tools.file.sync.model.base.BaseSyncInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SyncInfo extends BaseSyncInfo<SyncInfo> {
	public static final SyncInfo dao = new SyncInfo().dao();
}

